TAB        = _{ "\t" }
WHITESPACE = _{ " " | TAB | NEWLINE }

COLUMN_VALUE_CHAR = ${ !(TAB | NEWLINE) ~ ANY }

column_value = { COLUMN_VALUE_CHAR+ }

token_line = ${
    column_value ~ (TAB ~ column_value)* ~ &(NEWLINE | EOI)
}

TAG_VALUE_CHAR = ${ !(NEWLINE) ~ ANY }
tag_value      =  { TAG_VALUE_CHAR+ }

tag_line = ${
    "<" ~ tag_value ~ &(NEWLINE | EOI)
}

treetagger = ${
    SOI ~ ((tag_line | token_line) ~ NEWLINE?)+ ~ EOI
}
