on: push

name: Rust

jobs:
  format:
    name: Format Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          override: true
      - uses: mbrobbel/rustfmt-check@0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  static_code_analysis:
    name: Static code analysis
    needs: format
    runs-on: ubuntu-latest
    steps:
      - run: rustup component add clippy rustfmt
      - name: Install pyoxidizer crate
        uses: baptiste0928/cargo-install@v1
        with:
          crate: pyoxidizer
          version: "0.24"
      - uses: actions/checkout@v1
      - run: pyoxidizer generate-python-embedding-artifacts pyembedded
      - uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
  base_branch_cov:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          profile: minimal
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@v1.3.0
      - uses: SierraSoftworks/setup-grcov@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
      - name: Run tests with code coverage
        run: test_coverage.sh

      - name: Upload code coverage for ref branch
        uses: actions/upload-artifact@v2
        with:
          name: ref-lcov.info
          path: ./target/coverage/tests.lcov

  checks:
    runs-on: ubuntu-latest
    needs: base_branch_cov
    steps:
      - uses: actions/checkout@v2
      - name: Download code coverage report from base branch
        uses: actions/download-artifact@v2
        with:
          name: ref-lcov.info

      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          profile: minimal
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@v1.3.0
      - uses: SierraSoftworks/setup-grcov@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
      - name: Run tests with code coverage
        run: test_coverage.sh

      #  Compares two code coverage files and generates report as a comment
      - name: Generate Code Coverage report
        id: code-coverage
        uses: barecheck/code-coverage-action@v1
        with:
          barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
          lcov-file: "./target/coverage/tests.lcov"
          base-lcov-file: "./tests.lcov"
          minimum-ratio: 0 # Fails Github action once code coverage is decreasing
          send-summary-comment: true
          show-annotations: "warning" # Possible options warning|error