on:
  push:
  merge_group:

name: Rust

jobs:
  format:
    name: Format Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1.4.4
      - uses: mbrobbel/rustfmt-check@0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  static_code_analysis:
    name: Static code analysis
    needs: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rust-lang/setup-rust-toolchain@v1.4.4
        with:
          components: clippy
      - uses: actions/checkout@v4
      - name: Check code without default features
        run: cargo check --no-default-features
      - name: Check with clippy with all features enabled
        run: cargo clippy --all-features -- -D warnings
  unit-tests:
    env:
      RUST_BACKTRACE: 0
    name: Unit tests
    needs: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rust-lang/setup-rust-toolchain@v1.4.4
      - uses: actions/checkout@v4
      - name: Run unit tests
        run: cargo test
      - name: Compile CLI
        run: cargo build --bin annatto
      - name: 'Upload CLI Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: annatto-cli-debug
          path: target/debug/annatto
          retention-days: 5
    
  module_doc:
    name: Create module documentation
    runs-on: ubuntu-latest
    needs: [format, static_code_analysis, unit-tests]
    steps:
      - uses: actions/checkout@v4
      - name: Download annatto CLI
        uses: actions/download-artifact@v4
        with:
          name: annatto-cli-debug
      - name: Update documentation
        run: ./target/debug/annatto documentation docs/
      - name: Commit changed documentation
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          file_pattern: "docs/*"
          commit_message: Updating module documentation

