on: push
name: Static code analysis
jobs:
  static_code_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy rustfmt
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: fmt
          args: -- --check
      - uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
